# Generated by Django 2.0.3 on 2018-04-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.URLField(default='')),
                ('symbol', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('algorithm', models.CharField(max_length=64)),
                ('start_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
