# Generated by Django 2.0.3 on 2018-04-24 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Currencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCurrencyRateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open_rate', models.DecimalField(decimal_places=2, max_digits=16)),
                ('close_rate', models.DecimalField(decimal_places=2, max_digits=16)),
                ('high_rate', models.DecimalField(decimal_places=2, max_digits=16)),
                ('low_rate', models.DecimalField(decimal_places=2, max_digits=16)),
                ('adj_close', models.DecimalField(decimal_places=2, max_digits=16)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=16)),
                ('crypto_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Currencies.CryptoCurrency')),
            ],
        ),
    ]
