# Generated by Django 2.0.3 on 2018-06-29 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Currencies', '0002_cryptocurrencyratedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCurrencyRateDataChanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('changes', models.DecimalField(decimal_places=8, max_digits=16)),
                ('crypto_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Currencies.CryptoCurrency')),
            ],
        ),
    ]
